version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: manamana
      MYSQL_DATABASE: cidb
      MYSQL_USER: ciuser
      MYSQL_PASSWORD: manamana
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: manamana
    ports:
      - "8080:80"
    depends_on:
      - mariadb
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
